# Generated by Django 3.1.1 on 2021-05-31 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.IntegerField(db_index=True, unique=True)),
                ("guild_name", models.CharField(max_length=255)),
                ("channel_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.IntegerField(db_index=True)),
                ("discord_user", models.IntegerField()),
                ("url", models.CharField(max_length=255)),
                ("description", models.TextField(db_index=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord_data.channel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="channel",
            name="channel_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="discord_data.type"
            ),
        ),
    ]
