# Generated by Django 3.2.3 on 2021-05-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('discord_id', models.IntegerField()),
                ('discord_user', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.type')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('guild_name', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.type')),
            ],
        ),
    ]
